### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by xiaohui09** [HVision-NKU/StoryDiffusion#37]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 26.00 MiB (GPU 0; 6.00 GiB total capacity; 5.07 GiB already allocated; 0 bytes free; 5.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

how can i do? 
I tried use below code to set GPU and batch_size, and clean cache,but still had this error:
os.environ["CUDA_VISIABLE_DEVICES"] = "0"
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:128"
if hasattr(torch.cuda, "empty_cache"):
    torch.cuda.empty_cache()

**Comment by Z-YuPeng** [comment]
We now add a low GPU Memory cost version, it was tested on a machine with 24GB GPU memory (Tesla A10) and 30GB RAM and is expected to work well with >20 G GPU memory.

```python
python gradio_app_sdxl_specific_id_low_vram.py
```

**Comment by Speedway1** [comment]
> We now add a low GPU Memory cost version, it was tested on a machine with 24GB GPU memory (Tesla A10) and 30GB RAM and is expected to work well with >20 G GPU memory.
> 
> ```python
> python gradio_app_sdxl_specific_id_low_vram.py
> ```

Low vram version is working very well on RTC 4090 with 24GB RAM. Very good work, team!

**Comment by SoftologyPro** [comment]
> We now add a low GPU Memory cost version, it was tested on a machine with 24GB GPU memory (Tesla A10) and 30GB RAM and is expected to work well with >20 G GPU memory.
> 
> ```python
> python gradio_app_sdxl_specific_id_low_vram.py
> ```

This version is incredible.  So much faster.  On a 4090 your first example 8 panel comic is now finished in only 59 seconds.

**Comment by xiaohui09** [comment]
> We now add a low GPU Memory cost version, it was tested on a machine with 24GB GPU memory (Tesla A10) and 30GB RAM and is expected to work well with >20 G GPU memory.
> 
> ```python
> python gradio_app_sdxl_specific_id_low_vram.py
> ```

Thanks for your help. Very good work!

**Comment by SoftologyPro** [comment]
One quick issue with the low VRAM script.
use_safetensors is Falso so it does not auto-download the models.
pipe = StableDiffusionXLPipeline.from_pretrained(sd_model_path, torch_dtype=torch.float16, use_safetensors = False)

**Comment by Z-YuPeng** [comment]
> One quick issue with the low VRAM script. use_safetensors is Falso so it does not auto-download the models. pipe = StableDiffusionXLPipeline.from_pretrained(sd_model_path, torch_dtype=torch.float16, use_safetensors = False)

Thanks for your feedback. I changed the use_safetensors = False because the repo does not have safe tensor files, I think it will still download automatically. Have you observed does not auto-download? 

https://huggingface.co/stablediffusionapi/sdxl-unstable-diffusers-y/tree/main/unet

**Comment by SoftologyPro** [comment]
I load the gradio (low VRAM) click the first example, change the sd_type to Juggernaut and click Generate.
Gives the error
`OSError: Could not find the necessary `safetensors` weights in {'text_encoder_2/pytorch_model.bin', 'text_encoder/pytorch_model.bin', 'unet/diffusion_pytorch_model.bin', 'vae/diffusion_pytorch_model.bin'} (variant=None)`
Just to be sure I deleted the 
hub\models--RunDiffusion--Juggernaut-XL-v8
directory from my cache files and tried again.  Same error.
Then I cange line 450 to
`pipe = StableDiffusionXLPipeline.from_pretrained(sd_model_path, torch_dtype=torch.float16, use_safetensors = True)`
and try again.  Same error.
`OSError: Could not find the necessary `safetensors` weights in {'vae/diffusion_pytorch_model.bin', 'text_encoder/pytorch_model.bin', 'text_encoder_2/pytorch_model.bin', 'unet/diffusion_pytorch_model.bin'} (variant=None)`

**Comment by Z-YuPeng** [comment]
@SoftologyPro  Hi, The repo of Juggernaut does not have safatensors， I have modified the code use_safetensors = False, and works.

**Comment by Z-YuPeng** [comment]
Currently, the latest code has been tested on all four models and will not report errors. Please download the latest code and run "python gradio_app_sdxl_specific_id_low_vram.py".

**Comment by Z-YuPeng** [comment]
It seems that there are some issues with the junglenaut weight, and it cannot generate normally. It has been urgently removed from the model list.

**Comment by SoftologyPro** [comment]
OK, Juggernaut did download OK here when I just tested.
The first example did get a poor result...
![image](https://github.com/HVision-NKU/StoryDiffusion/assets/47686889/f37a5dc3-400a-4bef-8255-753d45b8b42d)

**Comment by Z-YuPeng** [comment]
@SoftologyPro You are right, Perhaps there was an error in loading the model's precision conversion for Juggernaut... I have found a solution and will update the code soon.

**Comment by SoftologyPro** [comment]
Juggernaut works now.  Thanks.

![image](https://github.com/HVision-NKU/StoryDiffusion/assets/47686889/ae2a3afb-36f9-44c9-b52a-3553b58448f0)
